# Extract required concepts for the low value care project.
# Pseudonymize all identifiers (hash and salt with project name)
# PREFIX sphn: <https://biomedit.ch/rdf/sphn-ontology/sphn#>
# CONSTRUCT a graph including only nodes of requested types + their outgoing edges
# NOTE: The resulting graph will contain URIs without types and likely be SHACL-invalid

PREFIX sphn: <https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX lucid: <https://biomedit.ch/rdf/sphn-schema/lucid#>

CONSTRUCT {
  ?s ?p ?o .
  ?o a ?ext_code .
}
WHERE {
  # Restrict to concepts of interest
  VALUES ?selected_concept {
    lucid:Answer
    lucid:FinancialCost
    lucid:Question
    lucid:Questionnaire
    lucid:QuestionnaireEvent
    lucid:ResponseOption
    sphn:AccessDevicePresence
    sphn:AdministrativeCase
    sphn:AdministrativeSex
    sphn:Age
    sphn:Assessment
    sphn:AssessmentComponent
    sphn:AssessmentEvent
    sphn:AssessmentResult
    sphn:BilledDiagnosis
    sphn:BilledDiagnosis_rank
    sphn:BilledProcedure
    sphn:BilledProcedure_rank
    sphn:BirthDate
    sphn:BloodPressure
    sphn:BloodPressureMeasurement
    sphn:BodyHeight
    sphn:BodyHeightMeasurement
    sphn:BodyMassIndex
    sphn:BodySite
    sphn:BodyTemperature
    sphn:BodyTemperatureMeasurement
    sphn:BodyWeight
    sphn:BodyWeightMeasurement
    sphn:CareHandling
    sphn:CivilStatus
    sphn:Code
    sphn:Consent
    sphn:DataDetermination
    sphn:DataProvider
    sphn:DeathDate
    sphn:Death
    sphn:Drug
    sphn:DrugAdministrationEvent
    sphn:DrugArticle
    sphn:DrugPrescription
    sphn:ElectrocardiographicProcedure
    sphn:Electrocardiogram
    sphn:HealthcareEncounter
    sphn:HeartRate
    sphn:HeartRateMeasurement
    sphn:ImagingProcedure
    sphn:InhaledOxygenConcentration
    sphn:InsuranceStatus
    sphn:Intent
    sphn:LabResult
    sphn:LabTest
    sphn:LabTestEvent
    sphn:Laterality
    sphn:Location
    sphn:MeasurementMethod
    sphn:MedicalDevice
    sphn:OxygenSaturation
    sphn:OxygenSaturationMeasurement
    sphn:Performer
    sphn:PharmaceuticalDoseForm
    sphn:PhysiologicState
    sphn:Quantity
    sphn:ResuscitationDirective
    sphn:ReferenceRange
    sphn:Sample
    sphn:SourceSystem
    sphn:SubjectPseudoIdentifier
    sphn:Substance
    sphn:TherapeuticArea
    sphn:TherapeuticArea_specialtyName
    sphn:TimePattern
    sphn:Unit
    sphn:ValueSet
  }
  # Instance nodes for each concept and their outgoing edges
  GRAPH <${SOURCE_GRAPH}> {
    ?s a ?selected_concept .
    ?s ?p ?o .
    # Include links to external code systems
    OPTIONAL {
      FILTER(STRENDS(STR(?p), "Code"))
      ?o a ?ext_code .
    }
  }
}
