# tripsu rules configuraiton file.

# hash URI of all nodes in the graph that are instances of an sphn concept,
# except for sphn:Code.
nodes:
  of_type:
    - "<https://www.biomedit.ch/rdf/sphn-schema/lucid#Answer>"
    - "<https://www.biomedit.ch/rdf/sphn-schema/lucid#FinancialCost>"
    - "<https://www.biomedit.ch/rdf/sphn-schema/lucid#Question>"
    - "<https://www.biomedit.ch/rdf/sphn-schema/lucid#Questionnaire>"
    - "<https://www.biomedit.ch/rdf/sphn-schema/lucid#QuestionnaireEvent>"
    - "<https://www.biomedit.ch/rdf/sphn-schema/lucid#ResponseOption>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AccessDevice>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AccessDevicePresence>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AdministrativeCase>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AdministrativeSex>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AdverseEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Age>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Allergen>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Allergy>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AllergyEpisode>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTestEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Assay>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Assessment>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AssessmentComponent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AssessmentEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#AssessmentResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BilledDiagnosis>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BilledProcedure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Biobanksample>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Birth>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BirthDate>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BloodPressure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BloodPressureMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyHeight>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyHeightMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyMassIndex>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyPosition>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodySite>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodySurfaceArea>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyTemperature>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyTemperatureMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyWeight>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#BodyWeightMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#CardiacIndex>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#CardiacOutput>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#CardiacOutputMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#CareHandling>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ChromosomalLocation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Chromosome>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Circumference>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#CircumferenceMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#CivilStatus>"
    #- "<https://biomedit.ch/rdf/sphn-schema/sphn#Code>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Consent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#CopyNumberVariation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Country>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DataDetermination>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DataFile>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DataProcessing>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DataProvider>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DataRelease>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Death>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DeathDate>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Department>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Diagnosis>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Drug>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DrugAdministrationEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DrugArticle>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Electrocardiogram>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ElectrocardiographicProcedure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ExcludedDisorder>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Exposure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#FluidBalance>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#FluidInputOutput>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#FollowUp>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Gene>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#GenePanel>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#GeneticVariation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#GenomicDeletion>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#GenomicInsertion>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#GenomicPosition>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#GestationalAgeAtBirth>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Hash>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#HealthcareEncounter>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#HealthcarePrimaryInformationSystem>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#HeartRate>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#HeartRateMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#HomeAddress>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ImagingProcedure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Implant>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ImplantPresence>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#InhaledOxygenConcentration>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#InsuranceStatus>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Intent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Interpretation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Isolate>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#LabAnalyzer>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#LabResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#LabTest>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#LabTestEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Laterality>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#LibraryPreparation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Location>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Measurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MedicalDevice>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MedicalProcedure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyMicroscopyLabTest>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyMicroscopyLabTestEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyMicroscopyResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicroorganismIdentificationLabTest>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicroorganismIdentificationLabTestEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#MicroorganismIdentificationResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Nationality>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#NursingDiagnosis>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#NutritionIntake>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#OncologyDiagnosis>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#OncologySurgery>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Organism>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#OrganSupport>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#OxygenSaturation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#OxygenSaturationMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Performer>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#PharmaceuticalDoseForm>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#PhysiologicState>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ProblemCondition>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Protein>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#QualityControlMetric>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Quantity>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#RadiotherapyProcedure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ReferenceInterpretation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ReferenceInterpretationResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ReferenceRange>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ReferenceSequence>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ReferenceValue>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#RespiratoryRate>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#RespiratoryRateMeasurement>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Result>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#ResuscitationDirective>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Sample>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SampleProcessing>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SemanticMapping>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SequencingAnalysis>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SequencingAssay>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SequencingInstrument>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SequencingRun>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Software>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SourceData>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SourceSystem>"
    #- "<https://biomedit.ch/rdf/sphn-schema/sphn#SPHNConcept>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#StandardOperatingProcedure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SubjectPseudoIdentifier>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Substance>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Terminology>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TherapeuticArea>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TimePattern>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TimeSeriesDataFile>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TobaccoExposure>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Transcript>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Transplant>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TransplantPresence>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorGradeAssessment>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorGradeAssessmentEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorGradeAssessmentResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorSpecimen>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorStageAssessment>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorStageAssessmentEvent>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorStageAssessmentResult>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#Unit>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#VariantDescriptor>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#VariantNotation>"
    - "<https://biomedit.ch/rdf/sphn-schema/sphn#VitalStatus>"

# Pseudonymize the (literal) value of hasIdentifier on all nodes in the graph.
objects:
  on_type_predicate:
    "<https://biomedit.ch/rdf/sphn-schema/sphn#AdministrativeCase>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#Assay>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#Biobanksample>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#Code>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#HealthcareEncounter>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#Isolate>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#Sample>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#SequencingAssay>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#SequencingRun>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#SubjectPseudoIdentifier>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
    "<https://biomedit.ch/rdf/sphn-schema/sphn#TumorSpecimen>":
      - "<https://biomedit.ch/rdf/sphn-schema/sphn#hasIdentifier>"
